# Generated by Django 4.1.8 on 2023-06-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='contratoReportado',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='id_equipoReportado',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='id_especialista',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='id_solucionCorta',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='id_ubicacion',
        ),
        migrations.DeleteModel(
            name='especialistas',
        ),
        migrations.DeleteModel(
            name='modeloEquipos',
        ),
        migrations.DeleteModel(
            name='ordenes',
        ),
        migrations.DeleteModel(
            name='proyectos',
        ),
        migrations.DeleteModel(
            name='soluciones',
        ),
        migrations.DeleteModel(
            name='ubicaciones',
        ),
    ]
