# Generated by Django 4.1.8 on 2023-10-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='contratoReportado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.proyectos', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='descripcionSoporte',
            field=models.TextField(blank=True, max_length=255, verbose_name='Descripcion Soporte'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='id_equipoReportado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.modeloequipos', verbose_name='Modelo Reportado'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='id_especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.especialistas', verbose_name='Especialista'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='id_solucionCorta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.soluciones', verbose_name='Solucion Corta'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='id_ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.ubicaciones', verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='solucionDetalle',
            field=models.TextField(blank=True, max_length=255, verbose_name='Solucion Detallada'),
        ),
        migrations.CreateModel(
            name='informaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreInformatico', models.CharField(default='Juan Diaz', max_length=100, verbose_name='Nombre Informatico')),
                ('fonoInformatico', models.IntegerField(default='56912345678', verbose_name='Telefono')),
                ('emailInformatico', models.CharField(max_length=100, verbose_name='Email')),
                ('tribunalInformatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.ubicaciones', verbose_name='Tribunal')),
            ],
        ),
    ]
